name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_RUNNING: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
      - name: Test with Django test and with shadow group access.
        run: |
          #sudo usermod -a -G shadow $USER
          #newgrp shadow << REALEND
          sudo useradd -m -G shadow testuser

          # Give access to workspace
          sudo chown -R testuser:testuser $GITHUB_WORKSPACE

          # Create the .django_pam file in repo root
          sudo cat << EOF > .django_pam
          guest
          zS3IKI!*%yfk
          guest@example.com
          EOF

          (cd example_site/settings
          ln -s development.py local.py
          ls -la local.py)

          # Run tests as that user, but explicitly use the same Python
          sudo -u testuser bash -c "
            export PATH=$pythonLocation/bin:\$PATH
            cd $GITHUB_WORKSPACE
            make tests
          "
      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2
