# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: django-pam

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    env:
      TEST_RUNNING: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors but, not undefined
          # names errors F821 and F822.
          flake8 --ignore=F821,F822 . --count --select=E9,F7,F63,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is
          # 127 chars wide, but Python is 80 characters.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with Django test and with shadow group access.
        run: |
          sudo usermod -a -G shadow $USER

          # Create the .django_pam file in repo root
          cat <<EOF > .django_pam
          guest
          zS3IKI!*%yfk
          guest@example.com
          EOF

          (cd example_site/settings
          ln -s development.py local.py
          ls -la local.py)
          echo "PATH=$PATH"
          which python
          which coverage
          sudo -u $USER env "PATH=$pythonLocation/bin:$PATH" make tests
